create table if not exists public.benchmark_events (
  id bigint generated by default as identity primary key,
  "schemaVersion" integer not null check ("schemaVersion" = 1),
  "installationId" uuid not null,
  "projectId" uuid not null,
  "packageVersion" text,
  event text not null check (event = 'telemetry_summary'),
  "timestamp" timestamptz not null,
  "sharingMode" text not null check ("sharingMode" = 'opt-in'),
  "clientProfiles" jsonb not null default '[]'::jsonb check (jsonb_typeof("clientProfiles") = 'array'),
  metrics jsonb not null check (jsonb_typeof(metrics) = 'object'),
  "insertedAt" timestamptz not null default timezone('utc', now())
);

create index if not exists benchmark_events_timestamp_idx
  on public.benchmark_events ("timestamp" desc);

create index if not exists benchmark_events_installation_project_idx
  on public.benchmark_events ("installationId", "projectId");

create index if not exists benchmark_events_metrics_gin_idx
  on public.benchmark_events
  using gin (metrics jsonb_path_ops);