/**
 * Self-contained HTML benchmark report exporter.
 *
 * Reads the benchmark history JSON and renders a single self-contained HTML file with
 * inlined trend charts (top-1 hit rate, MRR, page counts, lint findings, etc.). No
 * external assets or runtime dependencies — the file opens cleanly in any browser and is
 * the natural artifact to attach to a PR, share with a stakeholder, or print to PDF.
 *
 * Driven by `dendrite-wiki report:export [--output path] [--title text]`. When no
 * benchmark history exists yet, the exporter still produces a valid empty-state report
 * with instructions for capturing the first snapshot.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { readBenchmarkHistory, type DendriteBenchmarkHistoryArtifact, type DendriteBenchmarkSnapshot } from './benchmark.js';

export interface ReportExportOptions {
  root?: string;
  outputPath?: string;
  reportTitle?: string;
}

export interface ReportExportResult {
  outputPath: string;
  snapshotCount: number;
  bytesWritten: number;
  hasData: boolean;
}

const DEFAULT_TITLE = 'Dendrite Wiki MCP — Project Report';

export async function writeBenchmarkReportHtml(options: ReportExportOptions = {}): Promise<ReportExportResult> {
  const root = path.resolve(options.root ?? process.cwd());
  const outputPath = path.resolve(options.outputPath ?? path.join(root, 'docs', 'public', 'benchmark-report.html'));
  const title = options.reportTitle ?? DEFAULT_TITLE;

  const history = await readBenchmarkHistory(root);
  const html = renderReportHtml(history, { title });

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, html, 'utf8');
  const stat = await fs.stat(outputPath);

  return {
    outputPath,
    snapshotCount: history.snapshots.length,
    bytesWritten: stat.size,
    hasData: history.snapshots.length > 0
  };
}

interface RenderContext {
  title: string;
}

export function renderReportHtml(history: DendriteBenchmarkHistoryArtifact, context: RenderContext): string {
  const baseline = history.snapshots[0] ?? null;
  const latest = history.latest && history.latest.timestamp ? history.latest : history.snapshots.at(-1) ?? null;
  const generatedAt = new Date().toISOString();

  const summary = buildHeroSummary(baseline, latest);
  const metricCards = renderMetricCards(baseline, latest);
  const trendChart = renderTrendChart(history.snapshots);
  const recallPanel = renderRecallPanel(baseline, latest);
  const snapshotsTable = renderSnapshotsTable(history.snapshots);
  const emptyState = history.snapshots.length === 0
    ? '<section class="empty-state"><p>No benchmark snapshots yet. Run <code>npx dendrite-wiki benchmark:snapshot</code> to capture one, then re-export.</p></section>'
    : '';

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${escapeHtml(context.title)}</title>`,
    `<style>${REPORT_CSS}</style>`,
    '</head>',
    '<body>',
    '<main class="report">',
    '<header class="hero">',
    `<h1>${escapeHtml(context.title)}</h1>`,
    `<p class="meta">Generated ${escapeHtml(generatedAt)}${latest?.git?.commit ? ` · Commit <code>${escapeHtml(latest.git.commit)}</code>` : ''}${latest?.git?.branch ? ` · Branch <code>${escapeHtml(latest.git.branch)}</code>` : ''}</p>`,
    `<p class="summary">${escapeHtml(summary)}</p>`,
    '</header>',
    emptyState,
    metricCards,
    trendChart,
    recallPanel,
    snapshotsTable,
    '<footer class="footer">',
    '<p>Generated by <a href="https://github.com/mfillalan/dendrite-wiki-mcp">Dendrite Wiki MCP</a>. Local-first project memory and living wiki for AI coding agents.</p>',
    `<p class="footer-meta">Snapshots in this report: ${history.snapshots.length}</p>`,
    '</footer>',
    '</main>',
    '</body>',
    '</html>',
    ''
  ].join('\n');
}

function buildHeroSummary(baseline: DendriteBenchmarkSnapshot | null, latest: DendriteBenchmarkSnapshot | null): string {
  if (!baseline || !latest) {
    return 'No benchmark history yet — capture a snapshot to begin tracking project documentation health.';
  }

  if (baseline.timestamp === latest.timestamp) {
    return 'A baseline snapshot has been captured. Run more snapshots after meaningful sessions to start a trend.';
  }

  const baselineDebt = baseline.metrics.lintFindingCount + baseline.metrics.proposalCount + baseline.metrics.staleClaimCount;
  const latestDebt = latest.metrics.lintFindingCount + latest.metrics.proposalCount + latest.metrics.staleClaimCount;
  const coverageDelta = latest.metrics.metadataCoverage - baseline.metrics.metadataCoverage;

  if (latestDebt < baselineDebt && coverageDelta >= 0) {
    const debtDrop = baselineDebt - latestDebt;
    return `Documentation debt dropped by ${debtDrop} item${debtDrop === 1 ? '' : 's'} since the baseline. Wiki is healthier.`;
  }

  if (latestDebt > baselineDebt) {
    const debtRise = latestDebt - baselineDebt;
    return `Documentation debt grew by ${debtRise} item${debtRise === 1 ? '' : 's'} since the baseline. Review stale claims, lint findings, and proposals.`;
  }

  return 'The wiki is stable versus the baseline. Capture more snapshots after meaningful sessions to reveal a stronger trend.';
}

function renderMetricCards(baseline: DendriteBenchmarkSnapshot | null, latest: DendriteBenchmarkSnapshot | null): string {
  if (!baseline || !latest) {
    return '';
  }

  const cards = [
    metricCard('Wiki pages', latest.metrics.pageCount, baseline.metrics.pageCount, 'up'),
    metricCard('Source-backed claims', latest.metrics.claimCount, baseline.metrics.claimCount, 'up'),
    metricCard('Lint findings', latest.metrics.lintFindingCount, baseline.metrics.lintFindingCount, 'down'),
    metricCard('Open proposals', latest.metrics.proposalCount, baseline.metrics.proposalCount, 'down'),
    metricCard('Stale claims', latest.metrics.staleClaimCount, baseline.metrics.staleClaimCount, 'down'),
    metricCard('Metadata coverage', formatPercent(latest.metrics.metadataCoverage), formatPercent(baseline.metrics.metadataCoverage), 'up', latest.metrics.metadataCoverage - baseline.metrics.metadataCoverage)
  ];

  return ['<section class="metrics">', '<h2>Key Metrics</h2>', '<div class="metric-grid">', ...cards, '</div>', '</section>'].join('\n');
}

function metricCard(label: string, latestValue: number | string, baselineValue: number | string, betterDirection: 'up' | 'down', explicitDelta?: number): string {
  const numericLatest = typeof latestValue === 'number' ? latestValue : parseFloat(String(latestValue));
  const numericBaseline = typeof baselineValue === 'number' ? baselineValue : parseFloat(String(baselineValue));
  const delta = explicitDelta ?? numericLatest - numericBaseline;
  const deltaText = renderDelta(delta, typeof latestValue === 'string' && latestValue.endsWith('%'));
  const tone = deltaTone(delta, betterDirection);
  return [
    `<div class="metric-card metric-${tone}">`,
    `<span class="metric-label">${escapeHtml(label)}</span>`,
    `<span class="metric-value">${escapeHtml(String(latestValue))}</span>`,
    `<span class="metric-delta">${escapeHtml(deltaText)}</span>`,
    `<span class="metric-baseline">baseline ${escapeHtml(String(baselineValue))}</span>`,
    '</div>'
  ].join('');
}

function renderDelta(delta: number, isPercent: boolean): string {
  if (delta === 0) {
    return 'no change';
  }
  const sign = delta > 0 ? '+' : '';
  if (isPercent) {
    return `${sign}${(delta * 100).toFixed(1)}%`;
  }
  return `${sign}${delta}`;
}

function deltaTone(delta: number, betterDirection: 'up' | 'down'): 'good' | 'bad' | 'flat' {
  if (delta === 0) return 'flat';
  const isUp = delta > 0;
  if (betterDirection === 'up') return isUp ? 'good' : 'bad';
  return isUp ? 'bad' : 'good';
}

function renderTrendChart(snapshots: DendriteBenchmarkSnapshot[]): string {
  if (snapshots.length < 2) {
    return '';
  }

  const debtSeries = snapshots.map((s) => s.metrics.lintFindingCount + s.metrics.proposalCount + s.metrics.staleClaimCount);
  const claimSeries = snapshots.map((s) => s.metrics.claimCount);

  return [
    '<section class="trends">',
    '<h2>Health Trends</h2>',
    '<div class="trend-row">',
    trendBlock('Documentation debt (lint + proposals + stale claims)', debtSeries, 'bad'),
    trendBlock('Source-backed claims', claimSeries, 'good'),
    '</div>',
    '</section>'
  ].join('\n');
}

function trendBlock(label: string, series: number[], goodTone: 'good' | 'bad'): string {
  return [
    '<div class="trend-block">',
    `<h3>${escapeHtml(label)}</h3>`,
    inlineSparkline(series, goodTone),
    `<p class="trend-caption">${escapeHtml(`Range ${Math.min(...series)} → ${Math.max(...series)} across ${series.length} snapshots. Latest: ${series.at(-1) ?? 0}.`)}</p>`,
    '</div>'
  ].join('\n');
}

function inlineSparkline(series: number[], tone: 'good' | 'bad'): string {
  const width = 360;
  const height = 80;
  const padding = 6;
  if (series.length === 0) {
    return `<svg width="${width}" height="${height}" role="img" aria-label="No data"></svg>`;
  }

  const max = Math.max(...series, 1);
  const min = Math.min(...series, 0);
  const range = max - min || 1;
  const stepX = (width - padding * 2) / Math.max(series.length - 1, 1);
  const points = series
    .map((value, i) => {
      const x = padding + i * stepX;
      const y = height - padding - ((value - min) / range) * (height - padding * 2);
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(' ');

  const stroke = tone === 'good' ? '#247a4d' : '#b54728';
  const fill = tone === 'good' ? '#247a4d22' : '#b5472822';

  return [
    `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img">`,
    `<polyline fill="none" stroke="${stroke}" stroke-width="2" points="${points}" />`,
    `<polyline fill="${fill}" stroke="none" points="${points} ${(width - padding).toFixed(1)},${(height - padding).toFixed(1)} ${padding.toFixed(1)},${(height - padding).toFixed(1)}" />`,
    '</svg>'
  ].join('');
}

function renderRecallPanel(baseline: DendriteBenchmarkSnapshot | null, latest: DendriteBenchmarkSnapshot | null): string {
  if (!latest || !latest.recall || latest.recall.evaluatedProbeCount === 0) {
    return '';
  }

  const recall = latest.recall;
  const baselineRecall = baseline?.recall;
  const top1Pct = recall.evaluatedProbeCount > 0 ? (recall.top1HitCount / recall.evaluatedProbeCount) * 100 : 0;
  const top5Pct = recall.evaluatedProbeCount > 0 ? (recall.top5HitCount / recall.evaluatedProbeCount) * 100 : 0;

  return [
    '<section class="recall-panel">',
    '<h2>Recall Quality</h2>',
    `<p class="recall-source">Probe source: <code>${escapeHtml(recall.probesSource)}</code>${recall.probesPath ? ` · ${escapeHtml(recall.probesPath)}` : ''}</p>`,
    '<div class="recall-grid">',
    recallStat('Top-1 hit rate', `${top1Pct.toFixed(0)}%`, baselineRecall ? `${((baselineRecall.top1HitCount / Math.max(baselineRecall.evaluatedProbeCount, 1)) * 100).toFixed(0)}%` : '—'),
    recallStat('Top-5 hit rate', `${top5Pct.toFixed(0)}%`, baselineRecall ? `${((baselineRecall.top5HitCount / Math.max(baselineRecall.evaluatedProbeCount, 1)) * 100).toFixed(0)}%` : '—'),
    recallStat('Mean reciprocal rank', recall.meanReciprocalRank.toFixed(3), baselineRecall ? baselineRecall.meanReciprocalRank.toFixed(3) : '—'),
    recallStat('Misses', String(recall.missCount), baselineRecall ? String(baselineRecall.missCount) : '—'),
    recallStat('Probes evaluated', String(recall.evaluatedProbeCount), baselineRecall ? String(baselineRecall.evaluatedProbeCount) : '—'),
    '</div>',
    '</section>'
  ].join('\n');
}

function recallStat(label: string, value: string, baselineValue: string): string {
  return [
    '<div class="recall-stat">',
    `<span class="metric-label">${escapeHtml(label)}</span>`,
    `<span class="metric-value">${escapeHtml(value)}</span>`,
    `<span class="metric-baseline">baseline ${escapeHtml(baselineValue)}</span>`,
    '</div>'
  ].join('');
}

function renderSnapshotsTable(snapshots: DendriteBenchmarkSnapshot[]): string {
  if (snapshots.length === 0) {
    return '';
  }

  const rows = snapshots
    .map((s) => `<tr>
      <td>${escapeHtml(formatTimestamp(s.timestamp))}</td>
      <td>${escapeHtml(s.label)}</td>
      <td class="num">${s.metrics.pageCount}</td>
      <td class="num">${s.metrics.claimCount}</td>
      <td class="num">${s.metrics.lintFindingCount}</td>
      <td class="num">${s.metrics.proposalCount}</td>
      <td>${escapeHtml(s.git?.commit ?? '')}</td>
    </tr>`)
    .join('\n');

  return [
    '<section class="snapshots">',
    '<h2>All Snapshots</h2>',
    '<table>',
    '<thead><tr><th>Timestamp</th><th>Label</th><th>Pages</th><th>Claims</th><th>Lint</th><th>Proposals</th><th>Commit</th></tr></thead>',
    `<tbody>${rows}</tbody>`,
    '</table>',
    '</section>'
  ].join('\n');
}

function formatTimestamp(timestamp: string): string {
  if (!timestamp) return '—';
  return timestamp.replace('T', ' ').replace(/\.\d+Z$/, 'Z');
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(0)}%`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const REPORT_CSS = `
  :root {
    color-scheme: light;
    --ink: #172026;
    --muted: #5b6670;
    --line: #d7dee6;
    --panel: #ffffff;
    --bg: #f6f8fb;
    --good: #247a4d;
    --bad: #b54728;
    --flat: #5b6670;
    --accent: #2367d1;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--bg);
    color: var(--ink);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.5;
  }
  .report { max-width: 1080px; margin: 0 auto; padding: 32px 24px 64px; }
  .hero {
    background: linear-gradient(135deg, #ffffff 0%, #f0f6ff 100%);
    border: 1px solid var(--line);
    border-radius: 12px;
    padding: 32px;
    margin-bottom: 24px;
  }
  .hero h1 { margin: 0 0 8px; font-size: 28px; }
  .hero .meta { margin: 0 0 16px; color: var(--muted); font-size: 13px; }
  .hero .summary { margin: 0; font-size: 18px; font-weight: 500; color: var(--ink); }
  .empty-state { padding: 32px; text-align: center; color: var(--muted); border: 1px dashed var(--line); border-radius: 12px; margin-bottom: 24px; }
  section { margin-bottom: 32px; }
  section h2 { font-size: 18px; margin: 0 0 12px; color: var(--ink); }
  .metric-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 12px;
  }
  .metric-card, .recall-stat {
    background: var(--panel);
    border: 1px solid var(--line);
    border-radius: 10px;
    padding: 14px 16px;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .metric-label { font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.04em; }
  .metric-value { font-size: 24px; font-weight: 700; color: var(--ink); }
  .metric-delta { font-size: 13px; font-weight: 600; }
  .metric-baseline { font-size: 12px; color: var(--muted); }
  .metric-good .metric-delta { color: var(--good); }
  .metric-bad .metric-delta { color: var(--bad); }
  .metric-flat .metric-delta { color: var(--flat); }
  .trend-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; }
  .trend-block { background: var(--panel); border: 1px solid var(--line); border-radius: 10px; padding: 16px; }
  .trend-block h3 { margin: 0 0 8px; font-size: 14px; color: var(--ink); }
  .trend-block svg { display: block; max-width: 100%; height: auto; }
  .trend-caption { margin: 8px 0 0; color: var(--muted); font-size: 12px; }
  .recall-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; }
  .recall-source { color: var(--muted); font-size: 13px; margin: 0 0 12px; }
  table { width: 100%; border-collapse: collapse; background: var(--panel); border: 1px solid var(--line); border-radius: 10px; overflow: hidden; }
  th, td { padding: 10px 12px; text-align: left; font-size: 13px; border-bottom: 1px solid var(--line); }
  th { background: #fafbfd; color: var(--muted); font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; font-size: 11px; }
  tr:last-child td { border-bottom: none; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  code { font-family: 'SF Mono', Menlo, monospace; font-size: 12px; background: #eef2f7; padding: 1px 6px; border-radius: 4px; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; }
  .footer a { color: var(--accent); text-decoration: none; }
  .footer-meta { margin: 4px 0 0; }
`;
